version: '3.8'
services:
  php-apache-environment:
    container_name: surionAPI
    build:
        context: ./docker/php-apache
    volumes:
      - ./code:/var/www/html/
    ports:
      - 8003:80

